server:
  port: 8080
  ssl:
    key-store: file:/etc/letsencrypt/live/newsee.xyz/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}

spring:
  datasource:
    url: ${MYSQL_PROD_URL}
    username: ${MYSQL_PROD_USERNAME}
    password: ${MYSQL_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: ${JWT_SECRET_KEY}

security:
  kakao:
    client_id: ${CLIENT_ID}
    redirect_uri: ${REDIRECT_URI}
